repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.15'
    hooks:
    - id: ruff
      name: ruff
      pass_filenames: false
      args: ["--line-length", "120", "--fix", "--exclude", "./pjsip-bindings-fork"]
    - id: ruff-format
      name: ruff-format
      pass_filenames: false
      args: ["--line-length", "120", "--exclude", "./pjsip-bindings-fork"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        args: []
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]